import React, { useState } from "react";
import { Link, Navigate, useLocation } from "react-router";
import loginCheckpoint from "@/api/auth/loginCheckpoint";
import LoginFormContainer from "@/components/auth/LoginFormContainer";
import { useForm } from "react-hook-form";
import useFlash from "@/plugins/useFlash";
import FormField from "@/components/elements/FormField";
import Button from "@/components/elements/Button";

interface Values {
  code: string;
  recoveryCode: string;
}

const LoginCheckpointContainer = ({ token }: { token: string }) => {
  const { clearAndAddHttpError } = useFlash();
  const [isMissingDevice, setIsMissingDevice] = useState(false);

  const {
    register,
    handleSubmit,
    setValue,
    formState: { isSubmitting },
  } = useForm<Values>({
    defaultValues: {
      code: "",
      recoveryCode: "",
    },
  });

  const onSubmit = async (values: Values) => {
    try {
      const response = await loginCheckpoint(
        token,
        values.code,
        values.recoveryCode,
      );
      if (response.complete) {
        window.location.assign(response.intended || "/");
        return;
      }
    } catch (error) {
      console.error(error);
      clearAndAddHttpError({ error });
    }
  };

  return (
    <LoginFormContainer
      title={"Device Checkpoint"}
      className={"flex w-full"}
      onSubmit={handleSubmit(onSubmit)}
    >
      <div className={"mt-6"}>
        {isMissingDevice ? (
          <FormField
            label={"Recovery Code"}
            description={
              "Enter one of the recovery codes generated when you setup 2-Factor authentication on this account in order to continue."
            }
            type={"text"}
            autoComplete={"one-time-code"}
            autoFocus
            disabled={isSubmitting}
            {...register("recoveryCode")}
          />
        ) : (
          <FormField
            label={"Authentication Code"}
            description={"Enter the two-factor token generated by your device."}
            type={"text"}
            autoComplete={"one-time-code"}
            autoFocus
            disabled={isSubmitting}
            {...register("code")}
          />
        )}
      </div>
      <div className={"mt-6"}>
        <Button
          size={"xlarge"}
          type={"submit"}
          disabled={isSubmitting}
          isLoading={isSubmitting}
        >
          Continue
        </Button>
      </div>
      <div className={"mt-6 text-center"}>
        <span
          onClick={() => {
            setValue("code", "");
            setValue("recoveryCode", "");
            setIsMissingDevice((s) => !s);
          }}
          className={
            "cursor-pointer text-xs tracking-wide text-neutral-400 uppercase no-underline hover:text-neutral-200"
          }
        >
          {!isMissingDevice ? "I've Lost My Device" : "I Have My Device"}
        </span>
      </div>
      <div className={"mt-6 text-center"}>
        <Link
          to={"/auth/login"}
          className={
            "text-xs tracking-wide text-neutral-400 uppercase no-underline hover:text-neutral-200"
          }
        >
          Return to Login
        </Link>
      </div>
    </LoginFormContainer>
  );
};

export default () => {
  const location = useLocation();
  const state = location.state as { token?: string } | null;

  if (!state?.token) {
    return <Navigate to={"/auth/login"} replace />;
  }

  return <LoginCheckpointContainer token={state.token} />;
};
